/**
 * Load bundled dream entries (generated at build into functions/_data/dreams.json).
 * Never served as a static URL — only imported by authenticated dream APIs.
 */
export type DreamBundleEntry = {
	id: string;
	date: string;
	mood?: string;
	html: string;
	preview: string;
};

export type DreamBundle = {
	entries: DreamBundleEntry[];
	generatedAt: string | null;
};

// Generated by `npm run dreams:bundle` / prebuild. Stub ships empty.
import raw from '../_data/dreams.json';

export function getDreamBundle(): DreamBundle {
	const data = raw as DreamBundle;
	return {
		entries: Array.isArray(data.entries) ? data.entries : [],
		generatedAt: data.generatedAt ?? null,
	};
}

export function findDream(id: string): DreamBundleEntry | undefined {
	const safe = id.replace(/\\/g, '/').split('/').pop() ?? id;
	return getDreamBundle().entries.find((e) => e.id === safe || e.id === id);
}
